function [H,dH,ddH] = H_S(x,params)
%H_S First integral of slip model during stance

% Parameters
g = params.g;
k = params.k;
m = params.m;
l_0 = params.l_0;
    
% x_Stance = [alpha l dalpha dl]
H   = m*g*cos(x(1))*x(2)...
      +0.5*m*(x(2)^2*x(3)^2+x(4)^2)...
      +0.5*k*(x(2)-l_0)^2;
dH  = [-m*g*sin(x(1))*x(2),...
       m*g*cos(x(1))+m*x(2)*x(3)^2+k*(x(2)-l_0),...
       m*x(2)^2*x(3),...
       m*x(4)];
ddH = [-m*g*cos(x(1))*x(2),-m*g*sin(x(1)),0,0;...
       -m*g*sin(x(1)),m*x(3)^2+k,2*m*x(2)*x(3),0;...
       0,2*m*x(2)*x(3),m*x(2)^2,0;...
       0,0,0,m];
end
